# Generated by Django 3.0.2 on 2020-01-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is email verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='deteted at')),
                ('deleted_by_id', models.IntegerField(blank=True, null=True, verbose_name='deteted by')),
            ],
            options={
                'verbose_name': 'Hospital User',
                'verbose_name_plural': 'Hospital Users',
            },
        ),
    ]
