# Generated by Django 3.0.2 on 2020-01-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaluser',
            options={'verbose_name': 'Hospital User', 'verbose_name_plural': 'Users'},
        ),
    ]
